spring:
  application:
#    name: estimation-service
    name: ESTIMATION-SERV

server:
  port: 8085

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    hostname: localhost